name: grafana
version: 1.12.0
appVersion: 5.1.3
kubeVersion: "^1.8.0-0"
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
maintainers:
  - zanhsieh <zanhsieh@gmail.com> rtluckie <rluckie@cisco.com>
engine: gotpl
